version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: deploy/app.Dockerfile
    environment:
      MYSQl_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: concursos
      MYSQL_USER: concursos
      MYSQL_PASSWORD: 1R27pfeGVOrI
      MAIL_HOST: smtp.office365.com
      MAIL_PORT: 587
      MAIL_ENCRYPTION: tls
      MAIL_AUTHMODE: login
      MAIL_USER: concursos-NORESPONDER@uba.ar
      MAIL_USER_NAME: CONCURSOS UBA
      MAIL_PASSWORD: pH+GcJ4@Gn!wL7X2
      MAIL_ADMIN: admin@uba.ar
    ports:
      - '8080:80'
    networks:
      - concursos
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: concursos
      MYSQL_USER: concursos
      MYSQL_PASSWORD: 1R27pfeGVOrI
      MYSQL_ROOT_PASSWORD: 5cE19Iq_yH8h
    volumes:
      - ./deploy/database/concursos.sql:/docker-entrypoint-initdb.d/concursos.sql
      - database:/var/lib/mysql 
    networks:
      - concursos

networks:
  concursos:
    
volumes:
  database:
