version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: deploy/app.Dockerfile
    ports:
      - '8090:80'
    networks:
      - concursos     

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: concursos
      MYSQL_USER: concursos
      MYSQL_PASSWORD: 1R27pfeGVOrI
      MYSQL_ROOT_PASSWORD: 5cE19Iq_yH8h
    volumes:
      - ./deploy/database/concursos.sql:/docker-entrypoint-initdb.d/concursos.sql
      - database:/var/lib/mysql 
    networks:
      - concursos  

networks:
  concursos:

volumes:
  database:
