<?php

use yii\db\Migration;

/**
 * Class m240327_015549_insert_nuevos_concursos
 */
class m240327_015549_insert_nuevos_concursos extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-04652968- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,403,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05003399- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,404,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05018619- -UBA-DMESA#FCEN',1,4,4,NULL,3,NULL,287,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 16273539');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05164911- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,284,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-03623530- -UBA-DIMEDA#SA_FI',4,10,2,NULL, 1,NULL,405,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 11836699');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05213279- -UBA-DMEDA#FODON',4,12,4,NULL,1,NULL,NULL,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 21923670');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05300780- -UBA-DMEDA#FODON',3,12,2,NULL, 2,NULL,NULL,1,'2023-11-23','2024-04-08 00:00:00','09:00','18:00',NULL,'2023-11-22 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 10939189');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-02397009- -UBA-DMESA#FCEN',1,4,3,NULL,1,NULL,127,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 13994823');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05004502- -UBA-DMESA#FCEN',2,4,4,NULL,3,NULL,241,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05004557- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,406,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05018503- -UBA-DMESA#FCEN',1,4,3,NULL,1,NULL,159,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 18432564');

        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05003285- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,407,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05003795- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,150,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05004215- -UBA-DMESA#FCEN',2,4,4,NULL,3,NULL,231,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05138214- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,382,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05138264- -UBA-DMESA#FCEN',2,4,4,NULL,3,NULL,408,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05164318- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,160,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05233079- -UBA-DMESA#FCEN',2,4,4,NULL,3,NULL,287,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05254860- -UBA-DMESA#FCEN',2,4,4,NULL,1,NULL,304,2,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,'y/o aquellas materias que oportunamente se incorporen al plan de estudios o las materias que la autoridad departamental dispusiese',NULL,NULL,NULL,NULL,NULL,NULL);");
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05465307- -UBA-DMESA#SG_FVET',1,6,4,NULL,2,NULL,NULL,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 16164629');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05465416- -UBA-DMESA#SG_FVET',1,6,3,NULL,3,NULL,NULL,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 16432466');
        
        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05465474- -UBA-DMESA#SG_FVET',1,6,4,NULL,3,NULL,NULL,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 24963287');

        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05465535- -UBA-DMESA#SG_FVET',1,6,4,NULL,3,NULL,NULL,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 16505386');

        $this->execute("INSERT INTO concurso (numero_expediente, id_tipo_concurso, id_facultad, id_categoria, id_categoria_minima, id_dedicacion, id_dedicacion_minima, id_area_departamento, cantidad_de_puestos, fecha_inicio_inscripcion, fecha_fin_inscripcion, hora_inicio_inscripcion, hora_fin_inscripcion, id_tipo_informe, fecha_publicacion, cantidad_dias_publicacion, fecha_publicacion_prueba_oposicion, id_tipo_presupuesto, ultimo_numero_movimiento, comentario, lck_concurso, fecha_sorteo_publicada, fecha_entrevista_prueba_publicada, estado_propuesta_jurados_preliminar, estado_propuesta_preliminar, firmantes_comision_seleccionados) VALUES ('EX-2023-05121189- -UBA-DMEDA#FODON',4,12,4,NULL,2,NULL,NULL,1,'2023-12-12 00:00:00','2024-04-24 00:00:00','09:00','18:00',NULL,'2023-12-11 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);");
        $concurso_id = $this->db->getLastInsertID();
        $this->update('profile', ['concurso_id' => $concurso_id], 'numero_documento = 30312520');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m240327_015549_insert_nuevos_concursos cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m240327_015549_insert_nuevos_concursos cannot be reverted.\n";

        return false;
    }
    */
}
